version: '3'
services:
    backendservice:
        build: ./KeyCardWebServices/KeyCardWebServices
        ports:
        - "9000:80"
        - "9001:443"
    webfrontend:
        build: ./KeyCardWebFrontEnd/keycardfront
        ports:
        - "9100:80"
        - "3000:3000"
    iotfrontend:
        build: ./KeyCardIoTApp/KeyCardIoTApp